/*
Program 3.2

Computes the average and standard deviation of sequence of numbers
x_1,x_2,...,x_N of integers generated by rand.

Note we use a modified definition of the variance to avoid a double pass
over the data.

typedef localises the reference to the datatype being used for the underlying
computation.
*/

#include <tgmath.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <limits.h>
#include <time.h>

/**
 * @brief localised typedef for number type being used
 * 
 */
typedef int Number;

/**
 * @brief largest number we can generate
 * 
 */
#define NUM_MAX INT_MAX

/**
 * @brief Generates a random number up to
 * MIN(RAND_MAX, INT_MAX)
 * 
 * @return Number 
 */
Number randNum();

/**
 * @brief Calculate the average and standard deviation
 * of a collection of random numbers. 
 * 
 * @param argv[1] number of random numbers to generate
 * 
 * @return EXIT_SUCCESS on success, else EXIT_FAILURE
 * 
 */
int main(int argc, char* argv[argc + 1]) {

    if (argc != 2) {
        fprintf(stderr, "Usage: ./app N\n");
        return EXIT_FAILURE;
    }
    int N = atoi(argv[1]);
    double m1 = 0.0;
    double m2 = 0.0;

    Number x;
    srand(time(nullptr));

    for (size_t i = 0; i < N; i++) {
        x = randNum();
        m1 += ((double) x)/N;
        m2 += ((double) x*x) / N; 
    }
    printf("       Average: %f\n", m1);
    printf("Std. deviation: %f\n", sqrt(m2 - m1*m1));

    return EXIT_SUCCESS;
}

Number randNum() {
    return rand() % NUM_MAX;
}