/**
 * @file ex2_41.c
 * @author Felix Lempriere
 * @brief Solution to Exercise 2-41 from Chapter 2 of Sedgewick's Algorithms in
 * C.
 *
 * Compares the coefficients for the recurrences
 * C_{N} = C_{N/2}  + 1
 * C_{N} = C_{N/4}  + 1
 * C_{N} = C_{N/16} + 1
 *
 * The generalised solution is
 * C_{N} = log_{a}\left(N\right) + 1
 * Where alpha is the dividing factor in the recurrence and N is a power
 * of alpha.
 *
 * @version 0.1
 * @date 2025-04-13
 *
 * @copyright Copyright (c) 2025
 *
 */

#include <stdio.h>
#include <stdlib.h>

/**
 * @brief Compute log_{2^i}(n) where
 *
 * @param n Number to compute the logarithm of
 * @param i index of the power for the base of the logarithm, must be > 0.
 *
 * @note Behaviour undefined if i == 0 or n is not a power of the supplied
 *
 * @return size_t
 */
size_t log_power_of_two(size_t n, size_t i) {
    register size_t log_div_n;
    for (log_div_n = 0; n; log_div_n++, n >>= i);
    return log_div_n - 1;
}

/**
 * @brief Compares the coefficients generated by the recurrences
 * C_{N} = C_{N/2}  + 1
 * C_{N} = C_{N/4}  + 1
 * C_{N} = C_{N/16} + 1
 * Using the generalised solution:
 *      C_{N} = log_{a}\left(N\right) + 1
 * For N = 1, 2, 4, 8, 16, 32, 64, 128, 256 etc.
 * 
 * The results are printed in a tabular format.
 * @param argc 
 * @param argv 
 * @return EXIT_SUCCESS on successful exectution.
 */
int main(int argc, char* argv[argc + 1]) {
    /**
     * @brief Largest exponent for the power of two to calculate.
     *
     */
    constexpr size_t MAX_POWER = 8u;

    for (register size_t i = 0; i <= MAX_POWER; i++) {
        register size_t const x = (i) ? 2u << (i - 1u) : 1u;
        printf("N: %4zu\tlog2(N): %4zu\tlog4(N): %4zu\tlog16(N): %4zu\n", x,
               log_power_of_two(x, 1) + 1, log_power_of_two(x, 2) + 1,
               log_power_of_two(x, 4) + 1);
    }
    return EXIT_SUCCESS;
}