/**
 * @file ex2_43.c
 * @author Felix Lempriere
 * @brief Solution to Exercise 2-43 from Chapter 2 of Sedgewick's Algorithms in
 * C.
 *
 * Compares the coefficients for the recurrence, C_N = (C_{N/2})^2 with
 * the initial conditions
 * C_{1} = 1
 * C_{1} = 2 
 * C_{1} = 4
 *
 * The generalised solution is
 * C_{N} = \left(C_{1}\right)^N
 *
 * @version 0.1
 * @date 2025-04-13
 *
 * @copyright Copyright (c) 2025
 *
 */

 #include <stdio.h>
 #include <stdlib.h>
 
 /**
  * @brief Calculates the n-th coefficient of C_n for the reccurence,
  * C_N = \left(C_{N/2}\right)^2 with initial condition C_1 = c1.
  * 
  * The general solution of such a reccurence is
  * C_N = \left(C_1\right)^2
  * 
  * @param n Value to compute the coefficient of > 0.
  * @param i c1, initial condition.
  * 
  * @warning Behaviour is undefined if n == 0.
  * 
  * @return size_t The coefficient C_N.
  */
 size_t coefficient_N_given_c1(size_t n, size_t c1) {
    register size_t prod = c1;
    for (; n > 1; prod *= c1, n--);
    return prod;
 }
 
 /**
  * @brief Compares the coefficients generated by the recurrence
  * C_{N} = \left(C_{N/2}\right)^2
  * given the initial conditions C_1 = 1, 2, 4 for 1 <= N <= 10.
  *
  * The general solution to the recurrence is C_{N} = (C_{1})^N.
  * 
  * @param argc
  * @param argv
  * @return EXIT_SUCCESS on successful exectution.
  */
 int main(int argc, char* argv[argc + 1]) {
     /**
      * @brief Largest value of N to compute the coefficient of.
      * 
      * Chosen so as to not overflow 64 bit size_t type.
      */
     constexpr size_t N = 16u;
 
     for (register size_t i = 1; i <= N; i++) {
         printf("N: %4zu\t C_{1} == 1:  %4zu\tC_{1} == 2: %4zu\tC_{1} == 4: %4zu\n", i,
                coefficient_N_given_c1(i, 1),
                coefficient_N_given_c1(i, 2),
                coefficient_N_given_c1(i, 4));
     }
 
     return EXIT_SUCCESS;
 }