/**
 * @file NumberInt.c
 * @author Felix Lempriere
 * @brief Implements the Number interface for an unsigned integer type. Random
 * numbers are generated by generating a double in the range [0, 1) and
 * multiplying by upper_bound and truncating.
 * @version 0.1
 * @date 2025-04-02
 *
 * @copyright Copyright (c) 2025
 *
 */

#include "Interfaces/Number/v1/NumberInt/NumberInt.h"

#include "MacroLibrary/Random.h"

Number NUMBERrandom(Number const ub) { return CAST(Number)(RANDUNIFORM(ub)); }
